// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jylwcrxbtaeegiroapmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5bHdjcnhidGFlZWdpcm9hcG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMTI0MDQsImV4cCI6MjA1NDY4ODQwNH0.wwBWGSxY8_x_kuOxRMc-mhV-_evQhinUkNY4b4NhFTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);